#! /bin/bash

### START -------

$HOME/.config/polybar/forest/launch.sh &

pgrep -x sxhkd > /dev/null | sxhkd &

nitrogen --restore &

picom &

nm-applet & 
# remove cursor "x"
xsetroot -cursor_name left_ptr &

if [[ $(xrandr -q | grep "HDMI-1 connected") ]]; then
	bspc wm -O eDP-1 HDMI-1 
	bspc monitor eDP-1 -d 1 2 3 4
	bspc monitor HDMI-1 -d 5 6 7 8
else
	bspc wm -O eDP-1
	bspc monitor eDP-1 -d  1 2 3 4 5 6 7 8 9
fi



bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#E84F4F"

#bspc rule -a *:chrome desktop='^2'
#bspc rule -a google-chrome-unstable private=on dekstop=2
#bspc rule -a google-chrome-stable private=on dekstop=2
#bspc rule -a google-chrome-dev private=on dekstop=2
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenka manage=off
